cv_pdf/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('cv_to_pdf.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cv_to_pdf/urls.py
from django.urls import path
from cv_to_pdf.views import *

app_name = 'cv'

urlpatterns = [
    path('home/', BaseView.as_view(), name='home'),
    path('home/department_<int:pk>/', DepartmentDetail.as_view(), name='department_detail'),
    path('home/department_<int:pk>/group_<int:group_id>/', GroupDetail.as_view(), name='group_detail'),
    path('home/department_<int:pk>/group_<int:group_id>/<int:person>/', PersonDetail.as_view(), name='person_detail'),
    path('home/department_<int:pk>/group_<int:group_id>/<int:person>/info_<int:resume>/', ResumeDetail.as_view(), name='resume_info'),
    path('home/department_<int:pk>/group_<int:group_id>/<int:person>/<int:resume>/', ResumeView.as_view(), name='resume_detail'),
    path('home/department_<int:pk>/group_<int:group_id>/<int:person>/pdf_<int:resume>/', GeneratePDF.render_pdf, name='resume_pdf'),
]

cv_to_pdf/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models


class Department(models.Model):
    dep_name = models.CharField(max_length=255)

    def __str__(self):
        return self.dep_name

    def get_groups(self):
        return self.group_set.all()

    def get_groups_count(self):
        return self.group_set.count()


class Group(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE, default=None)
    group_name = models.CharField(max_length=255)

    def __str__(self):
        return self.group_name

    def get_employees(self):
        return self.person_set.all()

    def get_employees_count(self):
        return self.person_set.count()


class Person(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, default=None)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    ROLES = (
        ('Junior', 'Junior'),
        ('Middle', 'Middle'),
        ('Senior', 'Senior')
    )
    role = models.CharField(max_length=7, choices=ROLES, null=True)

    def __str__(self):
        return ' '.join([self.first_name, self.last_name])

    def get_full_name(self):
        return ' '.join([self.first_name, self.last_name])

    def get_resume(self):
        return self.resume_set.all()

    def get_resume_count(self):
        return self.resume_set.count()


class Resume(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE, default=None)
    role = models.CharField(max_length=255)

    def __str__(self):
        return self.person.get_full_name()

    def get_technical_expertise(self):
        return self.technicalexpertise_set.all().order_by('-index')

    def get_tool_and_framework(self):
        return self.toolandframework_set.all().order_by('-index')

    def get_project(self):
        return self.project_set.all()

    def get_communication(self):
        return self.communication_set.all().order_by('-index')

    def get_education(self):
        return self.education_set.all().order_by('-index')


class TechnicalExpertise(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, default=None)
    description = models.TextField()
    index = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.description[:10] + '...'


class ToolAndFramework(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, default=None)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    index = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.name


class Project(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, default=None)
    is_nda = models.BooleanField(default=False)
    project_title = models.CharField(max_length=255)
    nda_title = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField()
    team = models.CharField(max_length=255)
    role = models.CharField(max_length=255)
    skills = models.CharField(max_length=255)

    def __str__(self):
        return self.project_title


class Communication(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, default=None)
    description = models.TextField()
    index = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.description[:10] + '...'


class Education(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, default=None)
    place = models.CharField(max_length=255)
    specialization = models.CharField(max_length=255)
    year_of_ending = models.IntegerField(blank=True, null=True)
    index = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.place[:10] + '...'

cv_to_pdf/views.py
from __future__ import unicode_literals

from django.urls import reverse
from weasyprint import HTML
from django.views.generic import View, ListView, DetailView
from django.http import HttpResponse
from .models import *


class BaseView(ListView):
    model = Department
    template_name = 'cv_to_pdf/home_page.html'


class DepartmentDetail(DetailView):
    model = Department
    template_name = 'cv_to_pdf/department_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Department.objects.all()
        context['department'] = Department.objects.get(pk=kwargs['object'].pk)
        return context


class GroupDetail(DetailView):
    model = Group
    template_name = 'cv_to_pdf/group_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Department.objects.all()
        context['department'] = Department.objects.get(pk=kwargs['object'].department.pk)
        # context['group'] = Group.objects.get(pk=kwargs['object'].pk)
        return context

    def get_object(self, queryset=None):
        obj = Group.objects.get(pk=self.kwargs['group_id'])
        return obj


class PersonDetail(DetailView):
    model = Person
    template_name = 'cv_to_pdf/person_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Department.objects.all()
        context['department'] = Department.objects.get(pk=kwargs['object'].group.department.pk)
        context['group'] = Group.objects.get(pk=kwargs['object'].group.pk)
        return context

    def get_object(self, queryset=None):
        obj = Person.objects.get(pk=self.kwargs['person'])
        return obj


class ResumeDetail(DetailView):
    models = Resume
    template_name = 'cv_to_pdf/resume_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['department'] = Department.objects.get(pk=kwargs['object'].person.group.department.pk)
        context['group'] = Group.objects.get(pk=kwargs['object'].person.group.pk)
        context['person'] = Person.objects.get(pk=kwargs['object'].person.pk)
        return context

    def get_object(self, queryset=None):
        obj = Resume.objects.get(pk=self.kwargs['resume'])
        return obj


class ResumeView(DetailView):
    models = Resume
    template_name = 'cv_to_pdf/resume_detail.html'

    def get_object(self, queryset=None):
        obj = Resume.objects.get(pk=self.kwargs['resume'])
        return obj


class GeneratePDF(View):
    @staticmethod
    def render_pdf(self, **kwargs):
        html = HTML('http://127.0.0.1:8000/home/department_' +
                    str(kwargs['pk']) + '/group_' + str(kwargs['group_id']) + '/' +
                    str(kwargs['person']) + '/' + str(kwargs['resume']) + '/').write_pdf()
        response = HttpResponse(html, content_type='application/pdf')
        return response

cv_to_pdf/templates/cv_to_pdf/department_page.html
{% include 'cv_to_pdf/home_page.html' %}

{% block content %}
    <div class="group-list">
        <h1 class="first-name">{{ department.dep_name }} department:</h1>
        <h2 class="second-name">Groups:</h2>
        <table class="table">
            <tr>
                <th>Group name</th>
                <th>Number of people</th>
            </tr>
            {% for group in department.get_groups %}
                <tr>
                    <td>
                        <a href="{% url 'cv:group_detail' pk=department.id group_id=group.id %}" class="description-title">{{ group.group_name }}</a>
                    </td>
                    <td>
                        <span class="badge badge-primary badge-pill">Person: {{ group.get_employees_count }}</span>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

cv_to_pdf/templates/cv_to_pdf/group_page.html
{% include 'cv_to_pdf/home_page.html' %}

{% block content %}
    <div class="person-list" style="position: relative; z-index: 5">
        <div class="link-path">
            <a href="{% url 'cv:home' %}"><button class="button"><span class="glyphicon glyphicon-home"></span></button></a>
            <span class="glyphicon glyphicon-chevron-right"></span>
            <a href="{% url 'cv:department_detail' pk=object.department.id %}"><button class="button">{{ object.department.dep_name }}</button></a>
        </div>
        <h1 class="first-name">{{ group.group_name }}'s group:</h1>
        <div class="row">
            <div class="col-sm-13">
                {% for person in group.get_employees %}
                    <div class="col-sm-4 col-lg-3">
                        <div class="thumbnail">
                            <div class="caption">
                                <a href="{% url 'cv:person_detail' pk=department.id group_id=group.id person=person.id%}">
                                    <img src="../../../media/cv_to_pdf/images/user.png" class="img-responsive" style="background-color: lightgrey">
                                </a>
                                <h2>{{ person.first_name }} {{ person.last_name }}</h2>
                                <h4>{{ person.role }} developer</h4>

                                <!-- View Details -->
                                <a href="{% url 'cv:person_detail' pk=department.id group_id=group.id person=person.id %}" class="btn btn-primary btn-sm" role="button">
                                    View Details
                                </a>

                            </div>
                        </div>
                   </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

cv_to_pdf/templates/cv_to_pdf/home_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_department.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_group.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_person.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
{% block content %}
    <header>
        <a href="{% url 'cv:home' %}"><img src="https://www.nixsolutions.com/ru/wp-content/themes/nixsite6g/img/nix-logo.svg" alt="nixsolutions.com"></a>
    </header>
    <div class="navigationDesktop">
        <nav>
            <ul>
                <li><a href="{% url 'cv:home' %}">Home</a></li>
                <li><a>Departments <span class="glyphicon glyphicon-triangle-bottom"></span></a>
                    <ul style="position: relative; z-index: 7">
                        {% for department in object_list %}
                            <li>
                                <a href="{% url 'cv:department_detail' pk=department.id %}">
                                    {{ department.dep_name }}
                                    {% if department.get_groups %}
                                        <span class="glyphicon glyphicon-triangle-right"></span>
                                    {% endif %}
                                </a>
                                {% if department.get_groups %}
                                <ul>
                                    {% for group in department.get_groups %}
                                        <li><a href="{% url 'cv:group_detail' pk=department.id group_id=group.id %}">{{ group.group_name }}</a></li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}
</body>
</html>

cv_to_pdf/templates/cv_to_pdf/person_page.html
{% include 'cv_to_pdf/home_page.html' %}

{% block content %}
    <div style="margin-top: 2%; margin-left: 10%; width: 80%">
        <div class="link-path">
            <a href="{% url 'cv:home' %}"><button class="button"><span class="glyphicon glyphicon-home"></span></button></a>
            <span class="glyphicon glyphicon-chevron-right"></span>
            <a href="{% url 'cv:department_detail' pk=department.id %}"><button class="button">{{ department.dep_name }}</button></a>
            <span class="glyphicon glyphicon-chevron-right"></span>
            <a href="{% url 'cv:group_detail' pk=department.id group_id=group.id %}"><button class="button">{{ group.group_name }}</button></a>
        </div>

        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <img src="../../../../media/cv_to_pdf/images/user.png" class="img-responsive" class="img-responsive" style="background-color: lightgrey">
                    <h1>{{ person.first_name }} {{ person.last_name }}</h1>
                    <h2>{{ person.role }} <small>developer</small></h2>
                </div>
            </div>
        </div>

        <div class="col-sm-8 col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if person.get_resume %}
                        <h3>All resume</h3>
                    {% else %}
                        <h3 style="text-align: center"><b>There is no resume</b></h3>
                    {% endif %}
                    <table class="table">
                        <thead>
                            <tr>
                                <th>№</th>
                                <th>Job Role</th>
                                <th>Resume</th>
                                <th>PDF</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for resume in person.get_resume %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ resume.role }}</td>
                                    <td>
                                        <a href="{% url 'cv:resume_info' pk=department.id group_id=group.id person=person.id resume=resume.id %}">
                                            Preview <span class="glyphicon glyphicon-share-alt"></span>&nbsp;
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'cv:resume_pdf' pk=department.id group_id=group.id person=person.id resume=resume.id %}">
                                            <span class="glyphicon glyphicon-file"></span>&nbsp; .pdf
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

cv_to_pdf/templates/cv_to_pdf/resume_detail.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Session Feedback</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block content %}
        <div class="container">
            <div class="header">
                <div class="name">
                    <img src="{% static 'images/arrow-red.png' %}" alt="Arrow" class="arrow">
                    <h2 class="first-name">{{ object.person.first_name }}</h2>
                    <h2 class="second-name">{{ object.person.last_name }}</h2>
                    <img src="{% static 'images/arrow-blue.png' %}" alt="Arrow" class="arrow">
                </div>

                <div class="avatar">
                    <div class="user-photo-wrapper">
                        <img class="user-photo" src="{% static 'images/logo.png' %}" alt="User Photo">
                    </div>
                </div>
            </div>
            <div class="main">
                <div class="description-row">
                    <div class="left-side">
                        <h3 class="description-title bold upper">Role</h3>
                    </div>
                    <div class="right-side">
                        <p class="text">{{ object.role }}</p>
                    </div>
                </div>
                <div class="description-row">
                    <div class="left-side">
                        <h3 class="description-title">Technical Expertise</h3>
                    </div>
                    <div class="right-side">
                        {% for tech_exp in object.get_technical_expertise %}
                            <p class="text">{{ tech_exp.description }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="description-row">
                    <div class="left-side">
                        <h3 class="description-title">Tools &amp; Frameworks</h3>
                    </div>
                    <div class="right-side">
                        {% for tool in object.get_tool_and_framework %}
                            <p class="text">{{ tool.name }}: {{ tool.description }}</p>
                        {% endfor %}
                    </div>
                </div>

                <div class="description-row">
                    <div class="left-side">
                        <h3 class="description-title">Significant projects</h3>
                    </div>
                    <div class="right-side">
                        {% for project in object.get_project %}
                            <div class="text-container">
                                {% if project.is_nda %}
                                    <p class="text">{{ project.nda_title }}</p>
                                {% else %}
                                    <p class="text">{{ project.project_title }}</p>
                                {% endif %}
                                <p class="text">{{ project.description }}</p>
                                <p class="text">Team: {{ project.team }}</p>
                                <p class="text">Role: {{ project.role }}</p>
                                <p class="text">Skills: {{ project.skills }}</p>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="description-row">
                    <div class="left-side">
                        <h3 class="description-title">Communication</h3>
                    </div>
                    <div class="right-side">
                        {% for communication in object.get_communication %}
                            <p class="text">{{ communication.description }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="description-row">
                    <div class="left-side">
                        <h3 class="description-title">Education</h3>
                    </div>
                    <div class="right-side">
                        {% for education in object.get_education %}
                            <p class="text bold upper">{{ education.place }}</p>
                            <p class="text">{{ education.specialization }}, {{ education.year_of_ending }}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <div class="footer">
                <img src="{% static 'images/arrow-red.png' %}" alt="Arrow" class="arrow">
                <div class="nix-link">Nixsolutions.com</div>
                <img src="{% static 'images/arrow-blue.png' %}" alt="Arrow" class="arrow">
            </div>
        </div>
    {% endblock %}
</body>
</html>

cv_to_pdf/templates/cv_to_pdf/resume_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Session Feedback</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_group.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    {% block content %}
        <div>
            <div class="link-path">
                <div>
                    <a href="{% url 'cv:home' %}"><button class="button"><span class="glyphicon glyphicon-home"></span></button></a>
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <a href="{% url 'cv:department_detail' pk=department.id %}"><button class="button">{{ department.dep_name }}</button></a>
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <a href="{% url 'cv:group_detail' pk=department.id group_id=group.id %}"><button class="button">{{ group.group_name }}</button></a>
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <a href="{% url 'cv:person_detail' pk=department.id group_id=group.id person=person.id %}"><button class="button">{{ person.get_full_name }}</button></a>

                    <a href="{% url 'cv:resume_pdf' pk=department.id group_id=group.id person=person.id resume=resume.id %}" style="float: right"><button class="button">PDF<span class="glyphicon glyphicon-file"></span></button></a>
                </div>
            </div>

            <div class="container">
                <div class="header">
                    <div class="name">
                        <img src="../../../../../media/cv_to_pdf/images/arrow-red.png" alt="Arrow" class="arrow">
                        <h2 class="first-name">{{ object.person.first_name }}</h2>
                        <h2 class="second-name">{{ object.person.last_name }}</h2>
                        <img src="../../../../../media/cv_to_pdf/images/arrow-blue.png" alt="Arrow" class="arrow">
                    </div>

                    <div class="avatar">
                        <div class="user-photo-wrapper">
                            <img class="user-photo" src="../../../../../media/cv_to_pdf/images/logo.png" alt="User Photo">
                        </div>
                    </div>
                </div>
                <div class="main">
                    <div class="description-row">
                        <div class="left-side">
                            <h3 class="description-title bold upper">Role</h3>
                        </div>
                        <div class="right-side">
                            <p class="text">{{ object.role }}</p>
                        </div>
                    </div>
                    <div class="description-row">
                        <div class="left-side">
                            <h3 class="description-title">Technical Expertise</h3>
                        </div>
                        <div class="right-side">
                            {% for tech_exp in object.get_technical_expertise %}
                                <p class="text">{{ tech_exp.description }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="description-row">
                        <div class="left-side">
                            <h3 class="description-title">Tools &amp; Frameworks</h3>
                        </div>
                        <div class="right-side">
                            {% for tool in object.get_tool_and_framework %}
                                <p class="text">{{ tool.name }}: {{ tool.description }}</p>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="description-row">
                        <div class="left-side">
                            <h3 class="description-title">Significant projects</h3>
                        </div>
                        <div class="right-side">
                            {% for project in object.get_project %}
                                <div class="text-container">
                                    {% if project.is_nda %}
                                        <p class="text">{{ project.nda_title }}</p>
                                    {% else %}
                                        <p class="text">{{ project.project_title }}</p>
                                    {% endif %}
                                    <p class="text">{{ project.description }}</p>
                                    <p class="text">Team: {{ project.team }}</p>
                                    <p class="text">Role: {{ project.role }}</p>
                                    <p class="text">Skills: {{ project.skills }}</p>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="description-row">
                        <div class="left-side">
                            <h3 class="description-title">Communication</h3>
                        </div>
                        <div class="right-side">
                            {% for communication in object.get_communication %}
                                <p class="text">{{ communication.description }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="description-row">
                        <div class="left-side">
                            <h3 class="description-title">Education</h3>
                        </div>
                        <div class="right-side">
                            {% for education in object.get_education %}
                                <p class="text bold upper">{{ education.place }}</p>
                                <p class="text">{{ education.specialization }}, {{ education.year_of_ending }}</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <div class="footer">
                    <img src="../../../../../media/cv_to_pdf/images/arrow-red.png" alt="Arrow" class="arrow">
                    <div class="nix-link">Nixsolutions.com</div>
                    <img src="../../../../../media/cv_to_pdf/images/arrow-blue.png" alt="Arrow" class="arrow">
                </div>
            </div>
        </div>
    {% endblock %}
</body>
</html>